version: "3.9"

networks:
  net:
    driver: bridge

services:
  world:
    image: node:18
    command: npx ts-node src/app.ts
    volumes:
      - ./server:/app
    working_dir: /app
    networks:
      net:
        aliases:
          - world
    ports:
      - "3123:3123"
      - "8080:8080"

  agent1:
    image: node:18
    command: npx ts-node src/ag1.ts
    volumes:
      - ./server:/app
    working_dir: /app
    networks:
      - net
    depends_on:
      - world
    ports:
      - "3111:3111"

  agent2:
    image: node:18
    command: npx ts-node src/ag2.ts
    volumes:
      - ./server:/app
    working_dir: /app
    networks:
      - net
    depends_on:
      - world
    ports:
      - "3112:3112"

  agent3:
    image: node:18
    command: npx ts-node src/ag3.ts
    volumes:
      - ./server:/app
    working_dir: /app
    networks:
      - net
    depends_on:
      - world
    ports:
      - "3113:3113"

  agent4:
    image: node:18
    command: npx ts-node src/ag4.ts
    volumes:
      - ./server:/app
    working_dir: /app
    networks:
      - net
    depends_on:
      - world
    ports:
      - "3114:3114"

  frontend:
    build: ./frontend
    networks:
      - net
    depends_on:
      - world
    ports:
      - "3000:3000"
